### ISSUE TITLE
Validation tests for Assignment 3 - tail are not complete

### ISSUE THREAD

**Issue by titusvh** [HAN-ASD-DT/elm-assignment#1]
@dvberkel 
Not tested is if students solution correctly handles the tail of the tail...
I.e. [1,2,3, 4] will be 1, [2,3, 4].
After tail this should be 2,[3,4].

The validation tests only test a 1,[2] situation which returns only a NonEmptyList with a head. So if the student's solutions would screw up and would return 2,[] this would not be noticed by the validation.

I fixed this in my assignment file, just add
 `, test "tail of a longcons" (equal (Just (cons 51 (singleton 37))) (tail (cons 12 (cons 51 (singleton 37)))))`

**Comment by dvberkel** [comment]
@titusvh nice catch.

Could you provide a pullrequest?

**Comment by titusvh** [comment]
Done.
